services:
  db:
    container_name: aurora-db-deploy
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-aurora_db}
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - aurora_network

  users-service:
    # IMAGEM: troque USER_ORG/REPO e TAG se necess√°rio (ex.: ghcr.io/my-org/users-service:sha-<commit>)
    container_name: aurora-users-deploy
    image: ghcr.io/${REPO_OWNER}/users-service:${USERS_IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
      PORT: 3011
      DB_SCHEMA: users
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      SERVICE_TOKEN: ${SERVICE_TOKEN}
      HASH_PEPPER: ${HASH_PEPPER:-}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3011:3011"
    networks:
      - aurora_network

  auth-service:
    container_name: aurora-auth-deploy
    image: ghcr.io/${REPO_OWNER}/auth-service:${AUTH_IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
      PORT: 3010
      DB_SCHEMA: auth
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      USERS_API_URL: "http://users-service:3011"
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      SERVICE_TOKEN: ${SERVICE_TOKEN}
    depends_on:
      db:
        condition: service_healthy
      users-service:
        condition: service_started
    ports:
      - "3010:3010"
    networks:
      - aurora_network

  events-service:
    container_name: aurora-events-deploy
    image: ghcr.io/${REPO_OWNER}/events-service:${EVENTS_IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
      PORT: 3012
      DB_SCHEMA: events
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3012:3012"
    networks:
      - aurora_network

volumes:
  pgdata:

networks:
  aurora_network:
    driver: bridge
